name: CatUB Environment

on:
  push:
  workflow_dispatch:
   

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Cleanup workspace
        uses: rokibhasansagar/slimhub_actions@main

      - name: Setup init
        run: |
          sudo apt install -y python3-pip
          sudo apt install -y python3-dotenv

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${{ secrets.GHMAIL }}
          git config --global user.name ${{ secrets.GHUSER }}
          git config --global credential.helper store
          echo "https://${{ secrets.GHUSER }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone Mirror Repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GHUSER }}/${{ secrets.REPO }} nekopack 
          wget https://raw.githubusercontent.com/TgCatUB/catuserbot/master/requirements.txt
          wget https://raw.githubusercontent.com/ashty-drone/nekopack-helper/main/helper_script
          python3 helper_script
      - name: Installing requirements 
        run: |
          cd cat || exit 1
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install -r requirements.txt

      - name: Run bot
        continue-on-error: true
        timeout-minutes: 340
        run: |
          docker run --privileged --rm -i mirror-bot

      - name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          git commit --allow-empty -m "Workflow: Loop"
          git push -f
